### PR TITLE
Update pobfrontend to new fork with scaling support

### PR DESCRIPTION
**Pull request by ernstp**
I setup my own fork of pobfrontend to manage patches easier.

Includes this new commit: https://github.com/ernstp/pobfrontend/commit/5fa9fb714bf29f38436dd0164227f8622a94925c

### CODE REVIEW

**Comment by japz** [comment]
Thanks for the patch! I just tested this, it works for me. It would be nice to get this merged

**Comment by ernstp** [comment]
I had quite a few glitches with this still, but I'll take a look at it again soon!

**Comment by ernstp** [comment]
One could use something like

`flatpak override --user  --env=QT_SCALE_FACTOR=2 community.pathofbuilding.PathOfBuilding`

to set a specific scaling for PoB

**Comment by ernstp** [comment]
Should fix issue #39

**Pull request merged**
