### PR TITLE
Switch runtime to Qt6

### PR DESCRIPTION
**Pull request by ernstp**
I setup my own fork of pobfrontend to manage patches easier.

### CODE REVIEW

**Comment by ernstp** [comment]
Give this a test @nkukard @japz ?

**Comment by nkukard** [comment]
> Give this a test @nkukard @japz ?

Busy with it right now :), will revert soon.

**Comment by nkukard** [comment]
Working 100%, now that you forked pobfrontend, it would be very nice if we could get HiDPi working.

This looks like a very promising set of changes https://github.com/philroberts/pobfrontend/issues/6, but most hunks fail. Might need a bit of work.

**Comment by japz** [comment]
It runs for me, but the scaling is off: 
image

This is without `QT_` environment variables set

**Comment by ernstp** [comment]
This is still without any scaling support, just trying to modernize the basics first!

**Comment by ernstp** [comment]
I'm getting some weird "ghosting" graphics when dragging around the passive tree quickly...

**Comment by nkukard** [comment]
> I'm getting some weird "ghosting" graphics when dragging around the passive tree quickly...

What graphics adapter do you have btw?  I'm running one of this years AMD GPU's on Wayland under Arch.

**Comment by japz** [comment]
I tested this build, it works for me

**Comment by nkukard** [comment]
@ernstp tested my side running Arch, 1080p, AMD 5600 GPU, working 100%

did you by any chance have a moment to take a look at the HiDPi support?

**Comment by ernstp** [comment]
> @ernstp tested my side running Arch, 1080p, AMD 5600 GPU, working 100%
> 
> did you by any chance have a moment to take a look at the HiDPi support?

Thanks for testing!

Yeah I'm struggling with the graphics libraries, no progress on HiDPi yet...

**Pull request merged**
