### PR TITLE
Updated to PathOfBuilding v2.22.0

### PR DESCRIPTION
**Pull request by nkukard**
Update to v2.22.0, an additional dependency was required dkjson.

### CODE REVIEW

**Comment by nkukard** [comment]
Verified working!

**Comment by ernstp** [comment]
Ah cool, I will double check and merge this in a bit. Thanks for the help!

**Comment by nkukard** [comment]
> Ah cool, I will double check and merge this in a bit. Thanks for the help!

Only a pleasure, thanks for putting the effort into creating the Flatpak, it is really really appreciated.

**Comment by ernstp** [comment]
Ugh, did they force-push the tag to a new SHA1?!
https://github.com/flathub/community.pathofbuilding.PathOfBuilding/pull/27/commits/25ff169a7e1864d9e7092bcd238c4209895dee6c

**Comment by nkukard** [comment]
> Ugh, did they force-push the tag to a new SHA1?! [25ff169](https://github.com/flathub/community.pathofbuilding.PathOfBuilding/commit/25ff169a7e1864d9e7092bcd238c4209895dee6c)

The first one was the tag 2 minutes after they pushed it. Second one is a few minutes later after they fixed the .md file and the release was made.

**Review by ernstp — APPROVED** [review]

**Pull request merged**
